"""
Convert a TFLite binary model to a C header array for ESP32 firmware embedding.

Equivalent to running: xxd -i model.tflite > model_data.h
But cross-platform (no xxd required on Windows).

Usage:
    python scripts/conversion/model_to_c_array.py ml/models/int8/model.tflite firmware/esp32/main/model_data.h
"""

from __future__ import annotations

import sys
from pathlib import Path


def tflite_to_c_array(
    input_path: str,
    output_path: str,
    array_name: str = "kws_model_data",
    length_name: str = "kws_model_data_len",
    align: int = 8,
) -> None:
    """Convert a binary file to a C header with a byte array.

    Args:
        input_path: Path to the input binary file (e.g., model.tflite).
        output_path: Output path for the .h file.
        array_name: C identifier for the byte array.
        length_name: C identifier for the length variable.
        align: Memory alignment for the array (bytes).
    """
    data = Path(input_path).read_bytes()
    n_bytes = len(data)

    print(f"[convert] {input_path} → {output_path}")
    print(f"[convert] Model size: {n_bytes} bytes ({n_bytes/1024:.1f} KB)")

    lines = []
    lines.append("// Auto-generated by scripts/conversion/model_to_c_array.py")
    lines.append(f"// Source: {Path(input_path).name}")
    lines.append(f"// Size: {n_bytes} bytes ({n_bytes/1024:.1f} KB)")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"// TFLite model data — {n_bytes} bytes")
    lines.append(f"alignas({align}) const uint8_t {array_name}[] = {{")

    # Format bytes in rows of 16
    COLS = 16
    for i in range(0, n_bytes, COLS):
        chunk = data[i:i + COLS]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if (i + COLS) < n_bytes else ""
        lines.append(f"  {hex_vals}{comma}")

    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned int {length_name} = {n_bytes};")
    lines.append("")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text("\n".join(lines), encoding="ascii")
    print(f"[convert] Written: {output_path}")
    print(f"[convert] Array name: {array_name}[{n_bytes}]")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Convert TFLite model to C header array.")
    parser.add_argument("input", help="Input .tflite file")
    parser.add_argument("output", help="Output .h file")
    parser.add_argument("--name", default="kws_model_data", help="C array name")
    parser.add_argument("--align", type=int, default=8, help="Alignment in bytes")
    args = parser.parse_args()

    tflite_to_c_array(
        input_path=args.input,
        output_path=args.output,
        array_name=args.name,
        align=args.align,
    )
